export const SET_TOGGLE_SIDEBAR = 'SET_TOGGLE_SIDEBAR'

export const SET_VISITED_VIEWS = 'SET_VISITED_VIEWS'

export const SET_ROUTERS = 'SET_ROUTERS'

export const SET_ADD_ROUTERS = 'SET_ADD_ROUTERS'

export const SET_USER_CODE = 'SET_USER_CODE'

export const SET_USER_TYPE = 'SET_USER_TYPE'

export const SET_COMPANY_CODE = 'SET_COMPANY_CODE'

export const SET_TOKEN = 'SET_TOKEN'

export const SET_SETTING = 'SET_SETTING'

export const SET_STATUS = 'SET_STATUS'

export const SET_NAME = 'SET_NAME'

export const SET_AVATAR = 'SET_AVATAR'

export const SET_GENERATE = 'SET_GENERATE'

export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_LEFTSIDEBAR = 'SET_LEFTSIDEBAR'

export const SET_LEFTPARENT_SIDEBAR = 'SET_LEFTPARENT_SIDEBAR'

export const SET_GLOBAL_STRFLAG = 'SET_GLOBAL_STRFLAG'

export const SET_GLOBAL_TAGID = 'SET_GLOBAL_TAGID'

export const SET_VERTICAL_NAV_SHOW = 'SET_VERTICAL_NAV_SHOW'

export const SET_ISPC = 'SET_ISPC'
